package com.qrh.youshangdache.rules

import com.qrh.youshangdache.model.form.rules.FeeRuleRequest;
import java.math.BigDecimal;
import com.qrh.youshangdache.model.vo.rules.FeeRuleResponse;

global com.qrh.youshangdache.model.vo.rules.FeeRuleResponse feeRuleResponse;

/**
1.起步价
    00:00:00-06:59:59  19元(含3公里)
    07:00:00-23:59:59  19元(含5公里)
*/
rule "起步价 00:00:00-06:59:59  19元(含3公里)"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(startTime >= "00:00:00" && startTime <= "06:59:59")
    then
        feeRuleResponse = FeeRuleResponse.builder()
                        .baseDistance(new BigDecimal("3.0"))
                        .baseDistanceFee(new BigDecimal("19.0"))
                        .exceedDistance(new BigDecimal("0.0"))
                        .exceedDistancePrice(new BigDecimal("4.0"))
                        .build();
        System.out.printf("00:00:00-06:59:59，%s 公里，起步价: %s 元\n",
                       feeRuleResponse.getBaseDistance(),
                       feeRuleResponse.getBaseDistanceFee());
end

rule "起步价 07:00:00-23:59:59  19元(含5公里)"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(startTime >= "07:00:00" && startTime <= "23:59:59")
    then
        feeRuleResponse = FeeRuleResponse.builder()
                        .baseDistance(new BigDecimal("5.0"))
                        .baseDistanceFee(new BigDecimal("19.0"))
                        .exceedDistance(new BigDecimal("0.0"))
                        .exceedDistancePrice(new BigDecimal("3.0"))
                        .build();
        System.out.printf("07:00:00-23:59:59，%s 公里，起步价: %s 元\n",
                       feeRuleResponse.getBaseDistance(),
                       feeRuleResponse.getBaseDistanceFee());
end

/**
2.里程费
    超出起步里程后开始计算
    00:00:00-06:59:59   4元/1公里
    07:00:00-23:59:59   3元/1公里
*/
rule "里程费 00:00:00-06:59:59 4元/1公里"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(
            startTime >= "00:00:00"
            && startTime <= "06:59:59"
            && distance.compareTo(new BigDecimal("3.0")) > 0
        )
    then
        feeRuleResponse = feeRuleResponse.toBuilder()
                        .exceedDistance($rule.getDistance().subtract(new BigDecimal("3.0")))
                        .exceedDistancePrice(new BigDecimal("4.0"))
                        .build();
        System.out.printf("里程费，超出里程: %s 公里，单价：%s 元\n",
                       feeRuleResponse.getExceedDistance(),
                       feeRuleResponse.getExceedDistancePrice());
end

rule "里程费 07:00:00-23:59:59 3元/1公里"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(
            startTime >= "07:00:00"
            && startTime <= "23:59:59"
            && distance.compareTo(new BigDecimal("5.0")) > 0
        )
    then
        feeRuleResponse = feeRuleResponse.toBuilder()
                        .exceedDistance($rule.getDistance().subtract(new BigDecimal("5.0")))
                        .exceedDistancePrice(new BigDecimal("3.0"))
                        .build();
        System.out.printf("里程费，超出里程: %s 公里，单价：%s 元\n",
                        feeRuleResponse.getExceedDistance(),
                        feeRuleResponse.getExceedDistancePrice());
end

/**
3.等候费
    等候10分钟后  1元/1分钟
*/
rule "等候费 等候10分钟后 1元/1分钟"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(waitMinute > 10)
    then
        feeRuleResponse = feeRuleResponse.toBuilder()
                        .baseWaitMinute(10)
                        .exceedWaitMinute($rule.getWaitMinute() - 10)
                        .exceedWaitMinutePrice(BigDecimal.ONE)
                        .build();
        System.out.printf("等候费，超出 %s 分钟，单价：%s 元\n",
                        feeRuleResponse.getExceedWaitMinute(),
                        feeRuleResponse.getExceedWaitMinutePrice());
end
rule "无等候费"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(waitMinute <= 10)
    then
        feeRuleResponse = feeRuleResponse.toBuilder()
                        .baseWaitMinute(10)
                        .exceedWaitMinute(0)
                        .exceedWaitMinutePrice(BigDecimal.ONE)
                        .build();
        System.out.println("等候费：无");
end

/**
4.远途费
    订单行程超出12公里后每公里1元
*/
rule "远途费 订单行程超出12公里后每公里1元"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(distance.compareTo(new BigDecimal("12.0")) > 0)
    then
        feeRuleResponse = feeRuleResponse.toBuilder()
                        .baseLongDistance(new BigDecimal("12.0"))
                        .exceedLongDistance(
                            $rule.getDistance().subtract(new BigDecimal("12.0"))
                        )
                        .exceedLongDistancePrice(BigDecimal.ONE)
                        .build();
        System.out.printf("远途费，超出公里:%s 公里，单价：%s 元\n",
                        feeRuleResponse.getExceedLongDistance(),
                        feeRuleResponse.getExceedLongDistancePrice());
end
rule "无远途费"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(distance.compareTo(new BigDecimal("12.0")) <= 0)
    then
        feeRuleResponse = feeRuleResponse.toBuilder()
                        .baseLongDistance(new BigDecimal("12.0"))
                        .exceedLongDistance(BigDecimal.ZERO)
                        .exceedLongDistancePrice(BigDecimal.ZERO)
                        .build();
        System.out.println("远途费：无");
end

/**
5.计算总金额
    订单总金额 = 基础里程费 + 超出基础里程的费 + 等候费 + 远程费
*/
rule "计算总金额"
    salience 10
    no-loop true
    when
        $rule:FeeRuleRequest(distance.compareTo(new BigDecimal("0.0")) > 0)
    then
        BigDecimal distanceFee = feeRuleResponse.getBaseDistanceFee()
                                    .add(feeRuleResponse.getExceedDistance()
                                                .multiply(feeRuleResponse.getExceedDistancePrice())
                                    );
        BigDecimal waitFee = new BigDecimal(feeRuleResponse.getExceedWaitMinute())
                                .multiply(feeRuleResponse.getExceedWaitMinutePrice());
        BigDecimal longDistanceFee = feeRuleResponse.getExceedLongDistance()
                                        .multiply(feeRuleResponse.getExceedLongDistancePrice());
        BigDecimal totalAmount  = distanceFee.add(waitFee).add(longDistanceFee);
        feeRuleResponse = feeRuleResponse.toBuilder()
                        .distanceFee(distanceFee)
                        .waitFee(waitFee)
                        .longDistanceFee(longDistanceFee)
                        .totalAmount(totalAmount)
                        .build();
        System.out.println("计算总金额:" + feeRuleResponse.getTotalAmount() + "元");
end
