package com.qrh.youshangdache.rules

import com.qrh.youshangdache.model.form.rules.ProfitsharingRuleRequest;
import java.math.BigDecimal;
import java.math.RoundingMode
import com.qrh.youshangdache.model.vo.rules.ProfitsharingRuleResponse;

global com.qrh.youshangdache.model.vo.rules.ProfitsharingRuleResponse profitsharingRuleResponse;

/**
    支付微信平台费用 平台费率：0.6%
*/
rule "支付微信平台费用 平台费率：0.6%"
    salience 10
    no-loop true
    when
        $rule:ProfitsharingRuleRequest()
    then
        profitsharingRuleResponse = ProfitsharingRuleResponse.builder()
                        .orderAmount($rule.getOrderAmount())
                        .paymentRate(new BigDecimal("0.006"))
                        .paymentFee(
                            $rule.getOrderAmount()
                                .multiply(new BigDecimal("0.006"))
                                .setScale(2, RoundingMode.HALF_UP)
                        )
                        .build();
        System.out.printf("支付微信平台费用：%s 元\n",profitsharingRuleResponse.getPaymentFee());
end

/**
    订单金额小于等于100
        当天完成订单小于等于10单 平台抽成 20%
        当天完成订单大于10单 平台抽成 18%
*/
rule "订单金额小于等于100 当天完成订单小于等于10单"
    salience 10
    no-loop true
    when
        $rule:ProfitsharingRuleRequest(
            orderAmount.compareTo(new BigDecimal("100.0")) <= 0
            && orderNum <= 10
        )
    then
        BigDecimal totalAmount = profitsharingRuleResponse.getOrderAmount()
                                         .subtract(profitsharingRuleResponse.getPaymentFee());
        BigDecimal platformIncome = totalAmount.multiply(new BigDecimal("0.2"))
                                         .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverTotalIncome = totalAmount.subtract(platformIncome);
        BigDecimal driverTaxFee= driverTotalIncome.multiply(new BigDecimal("0.1"))
                                        .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverIncome= driverTotalIncome.subtract(driverTaxFee);
        profitsharingRuleResponse = profitsharingRuleResponse.toBuilder()
                        .platformIncome(platformIncome)
                        .driverIncome(driverIncome)
                        .driverTaxRate(new BigDecimal("0.1"))
                        .driverTaxFee(driverTaxFee)
                        .build();
        System.out.printf("平台分账收入：%s 元，司机分账收入：%s 元，司机个税：%s 元\n",
                       platformIncome, driverIncome, driverTaxFee);
end

rule "订单金额小于等于100 当天完成订单大于10单"
    salience 10
    no-loop true
    when
        $rule:ProfitsharingRuleRequest(
            orderAmount.compareTo(new BigDecimal("100.0")) <= 0
            && orderNum > 10
        )
    then
        BigDecimal totalAmount= profitsharingRuleResponse.getOrderAmount()
                                          .subtract(profitsharingRuleResponse.getPaymentFee());
        BigDecimal platformIncome = totalAmount.multiply(new BigDecimal("0.18"))
                                         .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverTotalIncome = totalAmount.subtract(platformIncome);
        BigDecimal driverTaxFee= driverTotalIncome.multiply(new BigDecimal("0.1"))
                                        .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverIncome= driverTotalIncome.subtract(driverTaxFee);
        profitsharingRuleResponse = profitsharingRuleResponse.toBuilder()
                        .platformIncome(platformIncome)
                        .driverIncome(driverIncome)
                        .driverTaxRate(new BigDecimal("0.1"))
                        .driverTaxFee(driverTaxFee)
                        .build();
        System.out.printf("平台分账收入：%s 元，司机分账收入：%s 元，司机个税：%s 元\n",
                       platformIncome, driverIncome, driverTaxFee);
end

/**
    订单金额大于100
        当天完成订单小于等于10单 平台抽成 18%
        当天完成订单大于10单 平台抽成 16%
*/
rule "订单金额大于100 当天完成订单小于等于10单"
    salience 10
    no-loop true
    when
        $rule:ProfitsharingRuleRequest(
            orderAmount.compareTo(new BigDecimal("100.0")) > 0
            && orderNum <= 10
        )
    then
        BigDecimal totalAmount = profitsharingRuleResponse.getOrderAmount()
                                        .subtract(profitsharingRuleResponse.getPaymentFee());
        BigDecimal platformIncome= totalAmount.multiply(new BigDecimal("0.18"))
                                        .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverTotalIncome= totalAmount.subtract(platformIncome);
        BigDecimal driverTaxFee= driverTotalIncome.multiply(new BigDecimal("0.1"))
                                        .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverIncome= driverTotalIncome.subtract(driverTaxFee);
        profitsharingRuleResponse = profitsharingRuleResponse.toBuilder()
                        .platformIncome(platformIncome)
                        .driverIncome(driverIncome)
                        .driverTaxRate(new BigDecimal("0.1"))
                        .driverTaxFee(driverTaxFee)
                        .build();
        System.out.printf("平台分账收入：%s 元，司机分账收入：%s 元，司机个税：%s 元\n",
                       platformIncome, driverIncome, driverTaxFee);
end
rule "订单金额大于100 当天完成订单大于10单"
    salience 10
    no-loop true
    when
        $rule:ProfitsharingRuleRequest(
            orderAmount.compareTo(new BigDecimal("100.0")) > 0
            && orderNum > 10
        )
    then
        BigDecimal totalAmount= profitsharingRuleResponse.getOrderAmount()
                                    .subtract(profitsharingRuleResponse.getPaymentFee());
        BigDecimal platformIncome = totalAmount.multiply(new BigDecimal("0.16"))
                                        .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverTotalIncome = totalAmount.subtract(platformIncome);
        BigDecimal driverTaxFee = driverTotalIncome.multiply(new BigDecimal("0.1"))
                                    .setScale(2, RoundingMode.HALF_UP);
        BigDecimal driverIncome = driverTotalIncome.subtract(driverTaxFee);
        profitsharingRuleResponse = profitsharingRuleResponse.toBuilder()
                        .platformIncome(platformIncome)
                        .driverIncome(driverIncome)
                        .driverTaxRate(new BigDecimal("0.1"))
                        .driverTaxFee(driverTaxFee)
                        .build();
        System.out.printf("平台分账收入：%s 元，司机分账收入：%s 元，司机个税：%s 元\n",
                       platformIncome, driverIncome, driverTaxFee);
end
