package com.qrh.youshangdache.rules

import com.qrh.youshangdache.model.form.rules.RewardRuleRequest;
import java.math.BigDecimal
import com.qrh.youshangdache.model.vo.rules.RewardRuleResponse;

global com.qrh.youshangdache.model.vo.rules.RewardRuleResponse rewardRuleResponse;

/**
    系统奖励
        00:00:00-06:59:59  完成5单后 每单奖励5元
        07:00:00-23:59:59  完成10单后 每单奖励2元
*/
rule "00:00:00-06:59:59  完成5单后 每单奖励5元"
    salience 10
    no-loop true
    when
        $rule:RewardRuleRequest(
            startTime >= "00:00:00"
            && startTime <= "06:59:59"
            && orderNum > 5
        )
    then
        rewardRuleResponse = RewardRuleResponse.builder()
                        .rewardAmount(new BigDecimal("5.0"))
                        .build();
        System.out.printf("00:00:00-06:59:59 奖励：%s 元\n",
                       rewardRuleResponse.getRewardAmount());
end
rule "07:00:00-23:59:59  完成10单后 每单奖励2元"
    salience 10
    no-loop true
    when
        $rule:RewardRuleRequest(
            startTime >= "07:00:00"
            && startTime <= "23:59:59"
            && orderNum > 10
        )
    then
        rewardRuleResponse = RewardRuleResponse.builder()
                        .rewardAmount(new BigDecimal("2.0"))
                        .build();
        System.out.printf("07:00:00-23:59:59 奖励：%s 元\n",
                       rewardRuleResponse.getRewardAmount());
end
