import subprocess, os

files = [
    # Feign clients (new paths)
    'service-client/src/main/java/com/qrh/youshangdache/coupon/feign/CouponFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/customer/feign/CustomerInfoFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/dispatch/feign/NewOrderFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/driver/feign/CiFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/driver/feign/CosFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/driver/feign/DriverAccountFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/driver/feign/DriverInfoFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/driver/feign/OcrFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/map/feign/LocationFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/map/feign/MapFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/order/feign/OrderInfoFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/order/feign/OrderMonitorFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/payment/feign/WxPayFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/rules/feign/FeeRuleFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/rules/feign/ProfitsharingRuleFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/rules/feign/RewardRuleFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SecurityLoginFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SysDeptFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SysLoginLogFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SysMenuFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SysOperLogFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SysPostFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SysRoleFeignClient.java',
    'service-client/src/main/java/com/qrh/youshangdache/system/feign/SysUserFeignClient.java',
    # service-util
    'service-util/src/main/java/com/qrh/youshangdache/common/aspect/LogAspect.java',
    'service-util/src/main/java/com/qrh/youshangdache/common/security/TokenLoginFilter.java',
    'service-util/src/main/java/com/qrh/youshangdache/common/security/UserDetailsServiceImpl.java',
    'service-util/src/main/java/com/qrh/youshangdache/common/security/WebSecurityConfig.java',
    # service
    'service/service-coupon/src/main/java/com/qrh/youshangdache/coupon/controller/CouponInfoController.java',
    'service/service-coupon/src/main/java/com/qrh/youshangdache/coupon/service/impl/CouponInfoServiceImpl.java',
    'service/service-customer/src/main/java/com/qrh/youshangdache/customer/controller/CustomerInfoController.java',
    'service/service-customer/src/main/java/com/qrh/youshangdache/customer/service/impl/CustomerInfoServiceImpl.java',
    'service/service-dispatch/src/main/java/com/qrh/youshangdache/dispatch/controller/NewOrderController.java',
    'service/service-dispatch/src/main/java/com/qrh/youshangdache/dispatch/service/impl/NewOrderServiceImpl.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/controller/CiController.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/controller/CosController.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/controller/DriverAccountController.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/controller/DriverInfoController.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/controller/OcrController.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/CiServiceImpl.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/CosServiceImpl.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/DriverAccountServiceImpl.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/DriverInfoServiceImpl.java',
    'service/service-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/OcrServiceImpl.java',
    'service/service-map/src/main/java/com/qrh/youshangdache/map/controller/LocationController.java',
    'service/service-map/src/main/java/com/qrh/youshangdache/map/controller/MapController.java',
    'service/service-map/src/main/java/com/qrh/youshangdache/map/service/impl/LocationServiceImpl.java',
    'service/service-map/src/main/java/com/qrh/youshangdache/map/service/impl/MapServiceImpl.java',
    'service/service-order/src/main/java/com/qrh/youshangdache/order/controller/OrderInfoController.java',
    'service/service-order/src/main/java/com/qrh/youshangdache/order/controller/OrderMonitorController.java',
    'service/service-order/src/main/java/com/qrh/youshangdache/order/service/impl/OrderInfoServiceImpl.java',
    'service/service-order/src/main/java/com/qrh/youshangdache/order/service/impl/OrderMonitorServiceImpl.java',
    'service/service-payment/src/main/java/com/qrh/youshangdache/payment/controller/WxPayController.java',
    'service/service-payment/src/main/java/com/qrh/youshangdache/payment/service/impl/WxPayServiceImpl.java',
    'service/service-payment/src/main/java/com/qrh/youshangdache/payment/service/impl/WxProfitsharingServiceImpl.java',
    'service/service-rules/src/main/java/com/qrh/youshangdache/rules/controller/FeeRuleController.java',
    'service/service-rules/src/main/java/com/qrh/youshangdache/rules/controller/ProfitSharingRuleController.java',
    'service/service-rules/src/main/java/com/qrh/youshangdache/rules/controller/RewardRuleController.java',
    'service/service-rules/src/main/java/com/qrh/youshangdache/rules/service/impl/FeeRuleServiceImpl.java',
    'service/service-rules/src/main/java/com/qrh/youshangdache/rules/service/impl/ProfitsharingRuleServiceImpl.java',
    'service/service-rules/src/main/java/com/qrh/youshangdache/rules/service/impl/RewardRuleServiceImpl.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SecurityLoginController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SysDeptController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SysLoginLogController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SysMenuController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SysOperLogController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SysPostController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SysRoleController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/controller/SysUserController.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/service/impl/SysDeptServiceImpl.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/service/impl/SysLoginLogServiceImpl.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/service/impl/SysMenuServiceImpl.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/service/impl/SysOperLogServiceImpl.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/service/impl/SysPostServiceImpl.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/service/impl/SysRoleServiceImpl.java',
    'service/service-system/src/main/java/com/qrh/youshangdache/system/service/impl/SysUserServiceImpl.java',
    # web
    'web/web-customer/src/main/java/com/qrh/youshangdache/customer/controller/CouponController.java',
    'web/web-customer/src/main/java/com/qrh/youshangdache/customer/controller/CustomerController.java',
    'web/web-customer/src/main/java/com/qrh/youshangdache/customer/controller/OrderController.java',
    'web/web-customer/src/main/java/com/qrh/youshangdache/customer/service/impl/CouponServiceImpl.java',
    'web/web-customer/src/main/java/com/qrh/youshangdache/customer/service/impl/CustomerServiceImpl.java',
    'web/web-customer/src/main/java/com/qrh/youshangdache/customer/service/impl/OrderServiceImpl.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/controller/CosController.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/controller/DriverController.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/controller/FileController.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/controller/LocationController.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/controller/MonitorController.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/controller/OcrController.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/controller/OrderController.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/CosServiceImpl.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/DriverServiceImpl.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/FileServiceImpl.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/LocationServiceImpl.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/MonitorServiceImpl.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/OcrServiceImpl.java',
    'web/web-driver/src/main/java/com/qrh/youshangdache/driver/service/impl/OrderServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/controller/SecurityLoginController.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/CustomerInfoServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/DriverInfoServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/OrderInfoServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/SysDeptServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/SysLoginLogServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/SysMenuServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/SysOperLogServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/SysPostServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/SysRoleServiceImpl.java',
    'web/web-mgr/src/main/java/com/qrh/youshangdache/mgr/service/impl/SysUserServiceImpl.java',
]

for f in files:
    result = subprocess.run(['git', 'add', f], capture_output=True, text=True)
    if result.returncode != 0:
        print(f'ERROR adding {f}: {result.stderr}')

print('Done staging files')
